"""
Script to populate countries table with all countries data.
Run this after running the migration: flask db upgrade
"""
from app import create_app
from app.extensions import db
from app.models import Country

# Comprehensive list of countries with ISO 3166-1 alpha-2 and alpha-3 codes
COUNTRIES_DATA = [
    {"name": "Afghanistan", "code": "AF", "code3": "AFG"},
    {"name": "Albania", "code": "AL", "code3": "ALB"},
    {"name": "Algeria", "code": "DZ", "code3": "DZA"},
    {"name": "Andorra", "code": "AD", "code3": "AND"},
    {"name": "Angola", "code": "AO", "code3": "AGO"},
    {"name": "Antigua and Barbuda", "code": "AG", "code3": "ATG"},
    {"name": "Argentina", "code": "AR", "code3": "ARG"},
    {"name": "Armenia", "code": "AM", "code3": "ARM"},
    {"name": "Australia", "code": "AU", "code3": "AUS"},
    {"name": "Austria", "code": "AT", "code3": "AUT"},
    {"name": "Azerbaijan", "code": "AZ", "code3": "AZE"},
    {"name": "Bahamas", "code": "BS", "code3": "BHS"},
    {"name": "Bahrain", "code": "BH", "code3": "BHR"},
    {"name": "Bangladesh", "code": "BD", "code3": "BGD"},
    {"name": "Barbados", "code": "BB", "code3": "BRB"},
    {"name": "Belarus", "code": "BY", "code3": "BLR"},
    {"name": "Belgium", "code": "BE", "code3": "BEL"},
    {"name": "Belize", "code": "BZ", "code3": "BLZ"},
    {"name": "Benin", "code": "BJ", "code3": "BEN"},
    {"name": "Bhutan", "code": "BT", "code3": "BTN"},
    {"name": "Bolivia", "code": "BO", "code3": "BOL"},
    {"name": "Bosnia and Herzegovina", "code": "BA", "code3": "BIH"},
    {"name": "Botswana", "code": "BW", "code3": "BWA"},
    {"name": "Brazil", "code": "BR", "code3": "BRA"},
    {"name": "Brunei", "code": "BN", "code3": "BRN"},
    {"name": "Bulgaria", "code": "BG", "code3": "BGR"},
    {"name": "Burkina Faso", "code": "BF", "code3": "BFA"},
    {"name": "Burundi", "code": "BI", "code3": "BDI"},
    {"name": "Cabo Verde", "code": "CV", "code3": "CPV"},
    {"name": "Cambodia", "code": "KH", "code3": "KHM"},
    {"name": "Cameroon", "code": "CM", "code3": "CMR"},
    {"name": "Canada", "code": "CA", "code3": "CAN"},
    {"name": "Central African Republic", "code": "CF", "code3": "CAF"},
    {"name": "Chad", "code": "TD", "code3": "TCD"},
    {"name": "Chile", "code": "CL", "code3": "CHL"},
    {"name": "China", "code": "CN", "code3": "CHN"},
    {"name": "Colombia", "code": "CO", "code3": "COL"},
    {"name": "Comoros", "code": "KM", "code3": "COM"},
    {"name": "Congo", "code": "CG", "code3": "COG"},
    {"name": "Costa Rica", "code": "CR", "code3": "CRI"},
    {"name": "Croatia", "code": "HR", "code3": "HRV"},
    {"name": "Cuba", "code": "CU", "code3": "CUB"},
    {"name": "Cyprus", "code": "CY", "code3": "CYP"},
    {"name": "Czech Republic", "code": "CZ", "code3": "CZE"},
    {"name": "Denmark", "code": "DK", "code3": "DNK"},
    {"name": "Djibouti", "code": "DJ", "code3": "DJI"},
    {"name": "Dominica", "code": "DM", "code3": "DMA"},
    {"name": "Dominican Republic", "code": "DO", "code3": "DOM"},
    {"name": "Ecuador", "code": "EC", "code3": "ECU"},
    {"name": "Egypt", "code": "EG", "code3": "EGY"},
    {"name": "El Salvador", "code": "SV", "code3": "SLV"},
    {"name": "Equatorial Guinea", "code": "GQ", "code3": "GNQ"},
    {"name": "Eritrea", "code": "ER", "code3": "ERI"},
    {"name": "Estonia", "code": "EE", "code3": "EST"},
    {"name": "Eswatini", "code": "SZ", "code3": "SWZ"},
    {"name": "Ethiopia", "code": "ET", "code3": "ETH"},
    {"name": "Fiji", "code": "FJ", "code3": "FJI"},
    {"name": "Finland", "code": "FI", "code3": "FIN"},
    {"name": "France", "code": "FR", "code3": "FRA"},
    {"name": "Gabon", "code": "GA", "code3": "GAB"},
    {"name": "Gambia", "code": "GM", "code3": "GMB"},
    {"name": "Georgia", "code": "GE", "code3": "GEO"},
    {"name": "Germany", "code": "DE", "code3": "DEU"},
    {"name": "Ghana", "code": "GH", "code3": "GHA"},
    {"name": "Greece", "code": "GR", "code3": "GRC"},
    {"name": "Grenada", "code": "GD", "code3": "GRD"},
    {"name": "Guatemala", "code": "GT", "code3": "GTM"},
    {"name": "Guinea", "code": "GN", "code3": "GIN"},
    {"name": "Guinea-Bissau", "code": "GW", "code3": "GNB"},
    {"name": "Guyana", "code": "GY", "code3": "GUY"},
    {"name": "Haiti", "code": "HT", "code3": "HTI"},
    {"name": "Honduras", "code": "HN", "code3": "HND"},
    {"name": "Hungary", "code": "HU", "code3": "HUN"},
    {"name": "Iceland", "code": "IS", "code3": "ISL"},
    {"name": "India", "code": "IN", "code3": "IND"},
    {"name": "Indonesia", "code": "ID", "code3": "IDN"},
    {"name": "Iran", "code": "IR", "code3": "IRN"},
    {"name": "Iraq", "code": "IQ", "code3": "IRQ"},
    {"name": "Ireland", "code": "IE", "code3": "IRL"},
    {"name": "Israel", "code": "IL", "code3": "ISR"},
    {"name": "Italy", "code": "IT", "code3": "ITA"},
    {"name": "Jamaica", "code": "JM", "code3": "JAM"},
    {"name": "Japan", "code": "JP", "code3": "JPN"},
    {"name": "Jordan", "code": "JO", "code3": "JOR"},
    {"name": "Kazakhstan", "code": "KZ", "code3": "KAZ"},
    {"name": "Kenya", "code": "KE", "code3": "KEN"},
    {"name": "Kiribati", "code": "KI", "code3": "KIR"},
    {"name": "Kosovo", "code": "XK", "code3": None},
    {"name": "Kuwait", "code": "KW", "code3": "KWT"},
    {"name": "Kyrgyzstan", "code": "KG", "code3": "KGZ"},
    {"name": "Laos", "code": "LA", "code3": "LAO"},
    {"name": "Latvia", "code": "LV", "code3": "LVA"},
    {"name": "Lebanon", "code": "LB", "code3": "LBN"},
    {"name": "Lesotho", "code": "LS", "code3": "LSO"},
    {"name": "Liberia", "code": "LR", "code3": "LBR"},
    {"name": "Libya", "code": "LY", "code3": "LBY"},
    {"name": "Liechtenstein", "code": "LI", "code3": "LIE"},
    {"name": "Lithuania", "code": "LT", "code3": "LTU"},
    {"name": "Luxembourg", "code": "LU", "code3": "LUX"},
    {"name": "Madagascar", "code": "MG", "code3": "MDG"},
    {"name": "Malawi", "code": "MW", "code3": "MWI"},
    {"name": "Malaysia", "code": "MY", "code3": "MYS"},
    {"name": "Maldives", "code": "MV", "code3": "MDV"},
    {"name": "Mali", "code": "ML", "code3": "MLI"},
    {"name": "Malta", "code": "MT", "code3": "MLT"},
    {"name": "Marshall Islands", "code": "MH", "code3": "MHL"},
    {"name": "Mauritania", "code": "MR", "code3": "MRT"},
    {"name": "Mauritius", "code": "MU", "code3": "MUS"},
    {"name": "Mexico", "code": "MX", "code3": "MEX"},
    {"name": "Micronesia", "code": "FM", "code3": "FSM"},
    {"name": "Moldova", "code": "MD", "code3": "MDA"},
    {"name": "Monaco", "code": "MC", "code3": "MCO"},
    {"name": "Mongolia", "code": "MN", "code3": "MNG"},
    {"name": "Montenegro", "code": "ME", "code3": "MNE"},
    {"name": "Morocco", "code": "MA", "code3": "MAR"},
    {"name": "Mozambique", "code": "MZ", "code3": "MOZ"},
    {"name": "Myanmar", "code": "MM", "code3": "MMR"},
    {"name": "Namibia", "code": "NA", "code3": "NAM"},
    {"name": "Nauru", "code": "NR", "code3": "NRU"},
    {"name": "Nepal", "code": "NP", "code3": "NPL"},
    {"name": "Netherlands", "code": "NL", "code3": "NLD"},
    {"name": "New Zealand", "code": "NZ", "code3": "NZL"},
    {"name": "Nicaragua", "code": "NI", "code3": "NIC"},
    {"name": "Niger", "code": "NE", "code3": "NER"},
    {"name": "Nigeria", "code": "NG", "code3": "NGA"},
    {"name": "North Korea", "code": "KP", "code3": "PRK"},
    {"name": "North Macedonia", "code": "MK", "code3": "MKD"},
    {"name": "Norway", "code": "NO", "code3": "NOR"},
    {"name": "Oman", "code": "OM", "code3": "OMN"},
    {"name": "Pakistan", "code": "PK", "code3": "PAK"},
    {"name": "Palau", "code": "PW", "code3": "PLW"},
    {"name": "Palestine", "code": "PS", "code3": "PSE"},
    {"name": "Panama", "code": "PA", "code3": "PAN"},
    {"name": "Papua New Guinea", "code": "PG", "code3": "PNG"},
    {"name": "Paraguay", "code": "PY", "code3": "PRY"},
    {"name": "Peru", "code": "PE", "code3": "PER"},
    {"name": "Philippines", "code": "PH", "code3": "PHL"},
    {"name": "Poland", "code": "PL", "code3": "POL"},
    {"name": "Portugal", "code": "PT", "code3": "PRT"},
    {"name": "Qatar", "code": "QA", "code3": "QAT"},
    {"name": "Romania", "code": "RO", "code3": "ROU"},
    {"name": "Russia", "code": "RU", "code3": "RUS"},
    {"name": "Rwanda", "code": "RW", "code3": "RWA"},
    {"name": "Saint Kitts and Nevis", "code": "KN", "code3": "KNA"},
    {"name": "Saint Lucia", "code": "LC", "code3": "LCA"},
    {"name": "Saint Vincent and the Grenadines", "code": "VC", "code3": "VCT"},
    {"name": "Samoa", "code": "WS", "code3": "WSM"},
    {"name": "San Marino", "code": "SM", "code3": "SMR"},
    {"name": "Sao Tome and Principe", "code": "ST", "code3": "STP"},
    {"name": "Saudi Arabia", "code": "SA", "code3": "SAU"},
    {"name": "Senegal", "code": "SN", "code3": "SEN"},
    {"name": "Serbia", "code": "RS", "code3": "SRB"},
    {"name": "Seychelles", "code": "SC", "code3": "SYC"},
    {"name": "Sierra Leone", "code": "SL", "code3": "SLE"},
    {"name": "Singapore", "code": "SG", "code3": "SGP"},
    {"name": "Slovakia", "code": "SK", "code3": "SVK"},
    {"name": "Slovenia", "code": "SI", "code3": "SVN"},
    {"name": "Solomon Islands", "code": "SB", "code3": "SLB"},
    {"name": "Somalia", "code": "SO", "code3": "SOM"},
    {"name": "South Africa", "code": "ZA", "code3": "ZAF"},
    {"name": "South Korea", "code": "KR", "code3": "KOR"},
    {"name": "South Sudan", "code": "SS", "code3": "SSD"},
    {"name": "Spain", "code": "ES", "code3": "ESP"},
    {"name": "Sri Lanka", "code": "LK", "code3": "LKA"},
    {"name": "Sudan", "code": "SD", "code3": "SDN"},
    {"name": "Suriname", "code": "SR", "code3": "SUR"},
    {"name": "Sweden", "code": "SE", "code3": "SWE"},
    {"name": "Switzerland", "code": "CH", "code3": "CHE"},
    {"name": "Syria", "code": "SY", "code3": "SYR"},
    {"name": "Taiwan", "code": "TW", "code3": "TWN"},
    {"name": "Tajikistan", "code": "TJ", "code3": "TJK"},
    {"name": "Tanzania", "code": "TZ", "code3": "TZA"},
    {"name": "Thailand", "code": "TH", "code3": "THA"},
    {"name": "Timor-Leste", "code": "TL", "code3": "TLS"},
    {"name": "Togo", "code": "TG", "code3": "TGO"},
    {"name": "Tonga", "code": "TO", "code3": "TON"},
    {"name": "Trinidad and Tobago", "code": "TT", "code3": "TTO"},
    {"name": "Tunisia", "code": "TN", "code3": "TUN"},
    {"name": "Turkey", "code": "TR", "code3": "TUR"},
    {"name": "Turkmenistan", "code": "TM", "code3": "TKM"},
    {"name": "Tuvalu", "code": "TV", "code3": "TUV"},
    {"name": "Uganda", "code": "UG", "code3": "UGA"},
    {"name": "Ukraine", "code": "UA", "code3": "UKR"},
    {"name": "United Arab Emirates", "code": "AE", "code3": "ARE"},
    {"name": "United Kingdom", "code": "GB", "code3": "GBR"},
    {"name": "United States", "code": "US", "code3": "USA"},
    {"name": "Uruguay", "code": "UY", "code3": "URY"},
    {"name": "Uzbekistan", "code": "UZ", "code3": "UZB"},
    {"name": "Vanuatu", "code": "VU", "code3": "VUT"},
    {"name": "Vatican City", "code": "VA", "code3": "VAT"},
    {"name": "Venezuela", "code": "VE", "code3": "VEN"},
    {"name": "Vietnam", "code": "VN", "code3": "VNM"},
    {"name": "Yemen", "code": "YE", "code3": "YEM"},
    {"name": "Zambia", "code": "ZM", "code3": "ZMB"},
    {"name": "Zimbabwe", "code": "ZW", "code3": "ZWE"},
]

def populate_countries():
    """Populate the countries table with all countries data."""
    app = create_app()
    with app.app_context():
        # Check if countries already exist
        if Country.query.count() > 0:
            print("Countries table already has data. Skipping population.")
            return
        
        print(f"Adding {len(COUNTRIES_DATA)} countries to the database...")
        for country_data in COUNTRIES_DATA:
            country = Country(
                name=country_data["name"],
                code=country_data["code"],
                code3=country_data.get("code3")
            )
            db.session.add(country)
        
        try:
            db.session.commit()
            print(f"Successfully added {len(COUNTRIES_DATA)} countries!")
        except Exception as e:
            db.session.rollback()
            print(f"Error adding countries: {e}")
            raise

if __name__ == "__main__":
    populate_countries()

