"""Add Flask-Security user/role tables

Revision ID: 0c4d8942138d
Revises: career_compass_init
Create Date: 2025-11-12 00:35:49.776584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c4d8942138d'
down_revision = 'career_compass_init'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('name', name=op.f('uq_role_name'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('fs_uniquifier', sa.String(length=64), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=100), nullable=True),
    sa.Column('current_login_ip', sa.String(length=100), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('fs_uniquifier', name=op.f('uq_user_fs_uniquifier'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_roles_users_role_id_role')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_roles_users_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_roles_users'))
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index('ix_answers_choice')
        batch_op.drop_index('ix_answers_question')
        batch_op.drop_index('ix_answers_session')

    #with op.batch_alter_table('categories', schema=None) as batch_op:
    #    batch_op.drop_constraint('categories_name_key', type_='unique')
    #    batch_op.create_unique_constraint(batch_op.f('uq_categories_name'), ['name'])

    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.drop_index('ix_choices_question_position')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index('ix_questions_category_position')

    #with op.batch_alter_table('respondents', schema=None) as batch_op:
    #    batch_op.drop_constraint('respondents_external_user_id_key', type_='unique')
    #    batch_op.create_unique_constraint(batch_op.f('uq_respondents_external_user_id'), ['external_user_id'])

    with op.batch_alter_table('response_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_response_sessions_respondent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_response_sessions_respondent', ['respondent_id'], unique=False)

    with op.batch_alter_table('respondents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_respondents_external_user_id'), type_='unique')
        batch_op.create_unique_constraint('respondents_external_user_id_key', ['external_user_id'])

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index('ix_questions_category_position', ['category_id', 'position'], unique=False)

    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.create_index('ix_choices_question_position', ['question_id', 'position'], unique=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_categories_name'), type_='unique')
        batch_op.create_unique_constraint('categories_name_key', ['name'])

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index('ix_answers_session', ['response_session_id'], unique=False)
        batch_op.create_index('ix_answers_question', ['question_id'], unique=False)
        batch_op.create_index('ix_answers_choice', ['choice_id'], unique=False)

    op.drop_table('roles_users')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
