"""add technical_questions and technical_choices

Revision ID: 4925a4f63214
Revises: 0c4d8942138d
Create Date: 2025-11-21 20:56:38.609526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

question_type_enum = postgresql.ENUM(
    "single", "multi", "scale", "text", "boolean", "number",
    name="question_type",
    create_type=False,  # ← DO NOT create the type again
)
# revision identifiers, used by Alembic.
revision = '4925a4f63214'
down_revision = '0c4d8942138d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technical_questions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('type', question_type_enum, nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_technical_questions_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_questions'))
    )
    op.create_table('technical_choices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['technical_questions.id'], name=op.f('fk_technical_choices_question_id_technical_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_choices')),
    sa.UniqueConstraint('question_id', 'value', name='uq_technical_choices_question_value')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technical_choices')
    op.drop_table('technical_questions')
    # ### end Alembic commands ###
