"""add new columns to courses table

Revision ID: 99f03f0ca0db
Revises: d5f6a7b8c9e0
Create Date: 2025-11-28 00:52:16.912258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99f03f0ca0db'
down_revision = 'd5f6a7b8c9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('platform', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('reviewcount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('certificatetype', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('crediteligibility', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_courses_user_id_user'), 'user', ['user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_courses_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('crediteligibility')
        batch_op.drop_column('certificatetype')
        batch_op.drop_column('duration')
        batch_op.drop_column('level')
        batch_op.drop_column('reviewcount')
        batch_op.drop_column('rating')
        batch_op.drop_column('skills')
        batch_op.drop_column('platform')
        batch_op.drop_column('course_title')

    # ### end Alembic commands ###
