"""add job_role_id to user table

Revision ID: b93a9d9073ef
Revises: 863df3c5d10c
Create Date: 2025-11-21 23:22:57.613993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93a9d9073ef'
down_revision = '863df3c5d10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_role_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_job_role_id_job_roles'), 'job_roles', ['job_role_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_job_role_id_job_roles'), type_='foreignkey')
        batch_op.drop_column('job_role_id')

    # ### end Alembic commands ###
