"""add countries table

Revision ID: c4e8f9a1b2c3
Revises: b93a9d9073ef
Create Date: 2025-11-21 23:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e8f9a1b2c3'
down_revision = 'b93a9d9073ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('code3', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries')),
    sa.UniqueConstraint('code', name=op.f('uq_countries_code')),
    sa.UniqueConstraint('code3', name=op.f('uq_countries_code3')),
    sa.UniqueConstraint('name', name=op.f('uq_countries_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries')
    # ### end Alembic commands ###

