"""add firstname lastname country_id to user table

Revision ID: d5f6a7b8c9e0
Revises: c4e8f9a1b2c3
Create Date: 2025-11-21 23:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f6a7b8c9e0'
down_revision = 'c4e8f9a1b2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_country_id_countries'), 'countries', ['country_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_country_id_countries'), type_='foreignkey')
        batch_op.drop_column('country_id')
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###

