"""add job_roles courses live_jobs tables and add job_roles_id to technical_questions

Revision ID: 863df3c5d10c
Revises: 4925a4f63214
Create Date: 2025-11-21 23:10:40.108001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863df3c5d10c'
down_revision = '4925a4f63214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_roles'))
    )
    op.create_table('courses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('job_roles_id', sa.BigInteger(), nullable=False),
    sa.Column('timeline', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_roles_id'], ['job_roles.id'], name=op.f('fk_courses_job_roles_id_job_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    op.create_table('live_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('salary', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('job_roles_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_roles_id'], ['job_roles.id'], name=op.f('fk_live_jobs_job_roles_id_job_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_jobs'))
    )
    with op.batch_alter_table('technical_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_roles_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_technical_questions_job_roles_id_job_roles'), 'job_roles', ['job_roles_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_questions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_technical_questions_job_roles_id_job_roles'), type_='foreignkey')
        batch_op.drop_column('job_roles_id')

    op.drop_table('live_jobs')
    op.drop_table('courses')
    op.drop_table('job_roles')
    # ### end Alembic commands ###
